# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-17 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmapPostion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('coordinate', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Positions',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='GmapTable',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='gmap_table_gmaptable', serialize=False, to='cms.CMSPlugin')),
                ('apiKey', models.CharField(max_length=100)),
                ('renderTemplate', models.CharField(blank=True, choices=[('gamp_table/Default.html', 'Default')], default='gamp_table/Default.html', max_length=150, verbose_name='GMap Table Template')),
            ],
            options={
                'verbose_name': 'GMap Table',
                'verbose_name_plural': 'GMap Table',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='gmappostion',
            name='gmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='gmap_table.GmapTable'),
        ),
    ]
